In [1]:
import numpy as np

In [6]:
# Tao mang
a = np.array([5,10,15])

# In mang
print(a)

# In ra 1 phan tu
element = a[1]
print(element)

[ 5 10 15]
10


In [7]:
# Tao mang 2 chieu
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)

# In 1 phan tu
element = matrix[2, 2]
print(element)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [13]:
# Cach tao mang
# Tao mang toan la so 0
a = np.zeros(6)
print(a)

# Tao mang toan la so 1
a = np.ones(5)
print(a)

# Tao mang
a = np.empty(4)
print(a)

# Tao mang tu 0 den 100
a = np.arange(100)
print(a)

# Tao mang gom cac phan tu voi khoang cach deu nhau
a = np.linspace(0, 10, num = 5)
print(a)


# Xac dinh kieu du lieu
a = np.ones(5, dtype = np.int64)
a

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 2.5  5.   7.5 10. ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [8]:
# Them, xoa, sap xep mang
# Tao mang ban dau
arr = np.array([6, 2, 3, 5, 8])
print(arr)

# Sap xep
arr = np.sort(arr)
print(arr)

# Sap xep nguoc
arr = np.sort(arr)[::-1]
print(arr)

# them phan tu vao mang
arr = np.append(arr, 100)
print(arr)

# Xoa di mot vi tri nao do trong mang
arr = np.delete(arr, 3)
print(arr)

[6 2 3 5 8]
[2 3 5 6 8]
[8 6 5 3 2]
[  8   6   5   3   2 100]
[  8   6   5   2 100]


In [10]:
# Tao mang 2 chieu
arr = np.array([[15, 1, 2],
                [4, 22, 8],
                [9, 10, 5]])

sap_xep_theo_hang = np.sort(arr, axis=1) # tang dan
print(sap_xep_theo_hang)

sap_xep_theo_cot = np.sort(arr, axis=0) # tang dan
print(sap_xep_theo_cot)

[[ 1  2 15]
 [ 4  8 22]
 [ 5  9 10]]
[[ 4  1  2]
 [ 9 10  5]
 [15 22  8]]


In [12]:
# tao mang 2 chieu
arr = np.array([[3, 1, 15],
                [11, 6, 8],
                [10, 7, 5]])

sap_xep_theo_hang = -np.sort(-arr, axis=1) # giam dan
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0) # giam dan
print(sap_xep_theo_cot)

[[15  3  1]
 [11  8  6]
 [10  7  5]]
[[11  7 15]
 [10  6  8]
 [ 3  1  5]]


In [13]:
# Tao mang 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Su dung thuoc tinh de lay thong tin cua mang
so_chieu = arr.ndim  # so chieu (2 chieu)
kich_thuoc = arr.size  # kich thuoc (tong so phan tu, 6)
hinh_dang = arr.shape  # hinh dang (so hang x so cot, (2, 3))

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [14]:
# Chuyen doi kieu du lieu
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [21]:
# Thay doi hinh dang cua mang
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [22]:
reshaped_arr = reshaped_arr.flatten() # Chuyen thanh mang 1 chieu
print(reshaped_arr)

[1 2 3 4 5 6]


In [23]:
# Cat lat mang
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  # Cat ohan tu tu thu nhat den thu tu
print(sub_arr) # 2 3 4 5

sub_arr = arr[:-1]  # 1 2 3 4
print(sub_arr)

sub_arr = arr[-2:]  # 4 5 
print(sub_arr)

[2 3 4]
[1 2 3 4]
[4 5]


In [24]:
# Chuyen vi mang
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# De chuyen vi mangm, chung ta co the su dung .T hoac ham numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [25]:
# Noi mang
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [26]:
# Ham tinh tong (Sum)
# Ham numpy.sum() cho phep tinh tong cac phan tu trong mang
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Tổng của mảng arr:", total)

# Ham tinh trung binh (Mean)
# Ham numpy.mean() tinh gia tri trung binh cua cac phan tu trong mang
average = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average)

# Ham tim gia tri nho nhat va lon nhat (Max và Min)
# Ham numpy.max() va numpy.min() tim gia tri nho nhat va lon nhat trong mang
max_value = np.max(arr)
min_value = np.min(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

# Ham tinh do lech chuan (Standard Deviation)
# Ham numpy.std() tinh do lech chuan cua mang, do luong muc do phan tan du lieu
std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

# Ham tinh phuong sai (Variance)
# Ham numpy.var() tinh phuong sai cua mang, do luong muc do bien thien cua du lieu
variance = np.var(arr)
print("Phương sai của mảng arr:", variance)

# Ham tinh tong tich chap (Dot Product)
# Ham numpy.dot() tinh tong tich chap cua 2 mang (vector).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của arr1 và arr2:", dot_product)

Tổng của mảng arr: 15
Giá trị trung bình của mảng arr: 3.0
Giá trị lớn nhất trong mảng arr: 5
Giá trị nhỏ nhất trong mảng arr: 1
Độ lệch chuẩn của mảng arr: 1.4142135623730951
Phương sai của mảng arr: 2.0
Tổng tích chập của arr1 và arr2: 32
